### PR TITLE
Ignore node modules

### LINKED ISSUE #1: Ignore node_modules and sass-cache?

### PR DESCRIPTION
**Pull request by IonicaBizau**
@zeke I removed and ignored the `node_modules` and `sass-cache` dirs. 💥 Fixes #1.

### CODE REVIEW

**Comment by zeke** [comment]
🍻

**Comment by IonicaBizau** [comment]
@zeke 🍸🍸 I don't drink beer. 😁 I never did it!

**Comment by zeke** [comment]
I don't either!

🍉 🍉

**Comment by IonicaBizau** [comment]
@zeke 👍 😁

**Pull request merged**
